import type { ContextRole } from "../context-pack.js";
import { PACKING_STRATEGY } from "../context-pack.js";

export const PACK_V1 = {
  strategy: PACKING_STRATEGY,
  maximumBudget: 1_000_000,
  searchCandidateLimit: 64,
  maximumCandidateSources: 64,
  maximumVerifiedBytes: 32 * 1024 * 1024,
  maximumDroppedCandidates: 32,
  wholeFileMaximumLines: 120,
  wholeFileMaximumTokens: 1_200,
  instructionMaximumTokens: 1_600,
  maximumInstructionSections: 4,
  surroundingLines: 3,
  enrichedSurroundingLines: 8,
  nearbyRangeMergeGap: 3,
  maximumImportLines: 24,
  maximumRelevantSymbolsPerLevel: [2, 4, 6] as const,
  maximumMarkdownSections: 3,
  boundedPrefixLines: 80,
  maximumLexicalRanges: 3,
  gitMaximumTokens: 128,
  maximumItems: {
    PRIMARY_CODE: 6,
    TEST: 4,
    DEPENDENCY: 4,
    DOCUMENTATION: 2,
    CONFIGURATION: 2,
  } satisfies Record<Exclude<ContextRole, "REPOSITORY_INSTRUCTION" | "GIT_CONTEXT">, number>,
  flexibleShares: {
    PRIMARY_CODE: 0.45,
    TEST: 0.15,
    DEPENDENCY: 0.15,
    DOCUMENTATION: 0.1,
    CONFIGURATION: 0.1,
  } satisfies Record<Exclude<ContextRole, "REPOSITORY_INSTRUCTION" | "GIT_CONTEXT">, number>,
  roleOrder: [
    "PRIMARY_CODE",
    "TEST",
    "DEPENDENCY",
    "DOCUMENTATION",
    "CONFIGURATION",
  ] as const,
  sectionOrder: [
    "REPOSITORY_INSTRUCTION",
    "PRIMARY_CODE",
    "TEST",
    "DEPENDENCY",
    "DOCUMENTATION",
    "CONFIGURATION",
    "GIT_CONTEXT",
  ] as const,
} as const;
