import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { chromium } from "playwright";
import { reviewFixture } from "./review-fixture.mjs";
const packageRoot = resolve(process.argv[2] ?? ".");
const load = (path) => import(pathToFileURL(join(packageRoot, "dist", path)));
const { createContextForgeLifecycle } = await load("composition/contextforge-lifecycle.js");
const { SqliteCapsuleHistory } = await load("adapters/sqlite/sqlite-capsule-history.js");
const { startStudio } = await load("adapters/studio/studio-server.js");
const { hashCapsuleCore, sha256, canonicalSerialize } = await load("core/context-capsule.js");
const root = await mkdtemp(join(tmpdir(), "contextforge-review-browser-"));
let browser, studio, history;
try {
  await reviewFixture(root);
  const app = await createContextForgeLifecycle(root);
  history = new SqliteCapsuleHistory(join(root, ".contextforge/history"));
  studio = await startStudio(app, history);
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1512, height: 1080 } });
  const errors = []; page.on("pageerror", (e) => errors.push(e.message));
  await page.goto(studio.url); await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  await page.locator("#review-budget").fill("1000");
  await page.getByRole("button", { name: "Build Review Context →", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Review Context saved" }).waitFor();
  assert.ok((await page.locator("#review-detail").textContent()).includes("ledger"));
  assert.ok(await page.locator(".impact-card").count() > 0);
  assert.ok((await page.locator("#review-summary").textContent()).includes("One hop"));
  await mkdir(".studio-output", { recursive: true });
  await page.screenshot({ path: ".studio-output/review-overview.png", fullPage: true });
  for (const width of [1024, 1280, 1920]) { await page.setViewportSize({ width, height: 1000 }); assert.ok(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth + 2)); }
  await page.setViewportSize({ width: 1512, height: 1080 });
  await page.getByRole("button", { name: "Context proposal", exact: true }).click();
  await page.locator("#filter").selectOption("DROPPED");
  assert.ok(await page.locator("#candidates tr").count() > 0, "Demo must demonstrate a real budget loss");
  const row = page.locator("#candidates tr").first(); await row.getByRole("combobox").selectOption("PIN");
  await page.getByRole("button", { name: "Recompile & compare", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "New Capsule saved" }).waitFor();
  assert.ok((await page.locator("#changes").textContent()).includes("DROPPED → SELECTED"));
  await page.screenshot({ path: ".studio-output/review-control-diff.png", fullPage: true });
  await page.getByRole("button", { name: "Replay", exact: true }).click();
  await page.getByRole("button", { name: "Verify replay", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Replay: EXACT_MATCH" }).waitFor();
  await page.getByRole("button", { name: "Exact context", exact: true }).click();
  assert.ok((await page.locator("#payload").textContent()).includes("<img src=x onerror="));
  assert.ok(!(await page.locator("body").textContent()).includes("REVIEW_SECRET_SENTINEL"));
  assert.equal(await page.evaluate(() => globalThis.injected), undefined);
  const hostile = history.get(history.list(1)[0].id);
  const r = hostile.deterministic.review;
  r.changes[0].symbols[0].name = "<img src=x onerror=globalThis.injected=true>";
  r.changeHash = sha256(canonicalSerialize({ base: r.base, head: r.head, changes: r.changes, excludedChanges: r.excludedChanges }));
  hostile.capsuleHash = hashCapsuleCore(hostile.deterministic); history.save(hostile);
  await page.reload(); await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  await page.locator(`.history-entry[data-id="${hostile.capsuleHash}"]`).click();
  await page.getByRole("status").filter({ hasText: "Saved metadata opened" }).waitFor();
  assert.ok((await page.locator("#review-detail").textContent()).includes("<img src=x"));
  assert.equal(await page.locator("#review-detail img").count(), 0);
  assert.equal(await page.evaluate(() => globalThis.injected), undefined);
  const token = new URL(studio.url).hash.slice(1);
  const response = await fetch(studio.origin + "/api", { method: "POST", headers: { Origin: studio.origin, Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: "review", base: "HEAD; echo injected", budget: 1000, refreshIndex: false }) });
  assert.equal(response.status, 400);
  assert.ok(!(await response.text()).includes(root));
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ version: "contextforge-review-browser-v1", passed: 1, failed: 0, skipped: 0, package: process.argv[2] ? "INSTALLED_PACKAGE" : "WORKTREE", browser: await browser.version(), viewports: [1024, 1280, 1512, 1920], journey: ["git-change", "impact", "budget-loss", "pin", "immutable-recompile", "semantic-diff", "exact-replay", "source-xss", "stored-metadata-xss", "ref-injection", "privacy"] }));
} finally { await browser?.close(); await studio?.close(); history?.close(); await rm(root, { recursive: true, force: true }); }
