import { view } from './studio-navigation.mjs';
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, rm, realpath } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { chromium } from "playwright";

// Optional installed package root makes the same journey a consumer-package gate.
const packageRoot = resolve(process.argv[2] ?? ".");
const { createContextForgeLifecycle } = await import(pathToFileURL(join(packageRoot, "dist/composition/contextforge-lifecycle.js")));
const { SqliteCapsuleHistory } = await import(pathToFileURL(join(packageRoot, "dist/adapters/sqlite/sqlite-capsule-history.js")));
const { startStudio } = await import(pathToFileURL(join(packageRoot, "dist/adapters/studio/studio-server.js")));
const root = await realpath(await mkdtemp(join(tmpdir(), "contextforge-studio-browser-")));
let browser, studio, history;
try {
  await mkdir(join(root, "src"));
  for (let i = 0; i < 12; i++) await writeFile(join(root, "src", `ledger${i}.ts`), `export function ledger${i}() {\n${Array.from({ length: 24 }, (_, n) => `  const value${n} = 'source_value_${i}_${n}';`).join("\n")}\n  return 'ledger';\n}\n`);
  await writeFile(join(root, "AGENTS.md"), "# Rules\nVerify changed ledger behavior.\n");
  await writeFile(join(root, ".env"), "STUDIO_BROWSER_SECRET=never_read\n");
  const app = await createContextForgeLifecycle(root);
  history = new SqliteCapsuleHistory(join(root, ".contextforge/history"));
  studio = await startStudio(app, history);
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1512, height: 1080 } });
  const remote = []; page.on("request", (r) => { if (new URL(r.url()).origin !== studio.origin) remote.push(r.url()); });
  const errors = []; page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(studio.url);
  await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  assert.equal(await page.title(), "RepoBound Studio");
  assert.ok((await page.locator(".brand").innerText()).includes("RepoBound"));
  await page.locator("#task").fill("fix ledger"); await page.locator("#budget").fill("2000");
  await page.getByRole("button", { name: "Build Context →", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Compiled and saved" }).waitFor();
  assert.ok(await page.locator("#candidates tr").count() > 1);
  await page.locator("#share").click();
  assert.deepEqual(await page.locator("#snapshot").evaluate((canvas) => [canvas.width, canvas.height]), [1200, 630]);
  const download = page.waitForEvent("download"); await page.locator("#snapshot-download").click();
  assert.match((await download).suggestedFilename(), /^repobound-context-[a-f0-9]{8}\.png$/u);
  await page.locator("#share-close").click();
  await view(page,"context");
  assert.ok((await page.locator("#payload").textContent()).includes("ContextForge Context Pack"));
  assert.ok(!(await page.locator("body").textContent()).includes("STUDIO_BROWSER_SECRET"));
  await view(page,"proposal");
  await page.locator("#candidates tr").filter({ has: page.locator(".tag.SELECTED") }).first().getByRole("button").click();
  await page.getByRole("status").filter({ hasText: "Explain: OK" }).waitFor();
  assert.ok((await page.locator("#explain").textContent()).includes("RECORDED DECISION"));
  await view(page,"proposal"); await page.locator("#filter").selectOption("DROPPED");
  const droppedRow = page.locator("#candidates tr").first(); await droppedRow.getByRole("button").click();
  await page.getByRole("status").filter({ hasText: "Explain: OK" }).waitFor();
  await view(page,"proposal"); await droppedRow.getByRole("combobox").selectOption("PIN");
  await view(page,"coverage");
  assert.ok((await page.locator("#coverage").textContent()).includes("BOUNDED CANDIDATES"));
  await page.getByRole("button", { name: "Rebuild context", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "New Capsule saved" }).waitFor();
  assert.ok((await page.locator("#changes").textContent()).includes("DROPPED → SELECTED"));
  await view(page,"replay");
  await page.getByRole("button", { name: "Verify replay", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Replay: EXACT_MATCH" }).waitFor();
  await page.reload(); await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  assert.equal(await page.locator(".history-entry").count(), 2);
  await page.locator('[data-nav="history"]').click(); await page.locator(".history-entry").first().click();
  await page.getByRole("status").filter({ hasText: "Saved metadata opened" }).waitFor();
  await view(page,"proposal");
  await page.locator("#filter").selectOption("ALL");
  await page.locator("#candidates tr").first().getByRole("button").click();
  await page.getByRole("status").filter({ hasText: "Explain: OK" }).waitFor();
  for (const [width,height] of [[1024,768],[1280,800],[1512,982],[1920,1080]]) {
    await page.setViewportSize({width,height});
    await view(page,"proposal");
    assert.ok(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth));
    assert.ok(await page.locator("#recompile").isVisible());
    await mkdir(".studio-output",{recursive:true});
    await page.screenshot({path: ".studio-output/studio-"+width+".png",fullPage:true});
  }
  await page.setViewportSize({width:1512,height:982});
  const screenshots = resolve(".studio-output"); await mkdir(screenshots, { recursive: true });
  await page.screenshot({ path: join(screenshots, "studio-workflow.png"), fullPage: true });
  await page.locator('[data-nav="context"]').click(); await page.locator("#mode-task").click();
  await page.locator("#task").fill("Investigate a deliberately long session synchronization task statement that must wrap safely in the 1200 by 630 Context Snapshot without hiding the budget or selected files <img src=x onerror=window.contextforgeInjected=true>");
  await page.locator("#refresh").uncheck();
  await page.getByRole("button", { name: "Build Context →", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Compiled and saved" }).waitFor();
  await page.locator("#share").click(); assert.ok((await page.locator("#snapshot").evaluate((canvas) => canvas.toDataURL("image/png").length)) > 1000); await page.locator("#share-close").click();
  assert.equal(await page.locator("img").count(), 0);
  assert.equal(await page.evaluate(() => globalThis.contextforgeInjected), undefined);
  await page.reload(); await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  assert.equal(await page.locator("img").count(), 0);
  assert.deepEqual(remote, []); assert.deepEqual(errors, []);
  // Restart proves durability and that historical source context is not persisted.
  await studio.close(); history.close(); history = new SqliteCapsuleHistory(join(root, ".contextforge/history"));
  studio = await startStudio(app, history); await page.goto(studio.url);
  await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  await page.locator('[data-nav="history"]').click(); await page.locator(".history-entry").first().click(); await view(page,"context");
  assert.ok((await page.locator("#payload").textContent()).includes("Exact context is not stored"));
  console.log(JSON.stringify({ schemaVersion: "contextforge-studio-e2e-v1", passed: 1, failed: 0, skipped: 0, journey: ["compile", "context", "selected-explain", "dropped-explain", "coverage", "history", "pin", "recompile", "semantic-diff", "exact-replay", "reload", "stored-xss", "restart-source-light"], packageRoot: process.argv[2] ? "INSTALLED_PACKAGE" : "WORKTREE", browser: await browser.version() }));
} finally { await browser?.close(); await studio?.close(); history?.close(); await rm(root, { recursive: true, force: true }); }
