import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, rm, realpath } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { chromium } from "playwright";

// Optional installed package root makes the same journey a consumer-package gate.
const packageRoot = resolve(process.argv[2] ?? ".");
const { createContextForgeLifecycle } = await import(pathToFileURL(join(packageRoot, "dist/composition/contextforge-lifecycle.js")));
const { SqliteCapsuleHistory } = await import(pathToFileURL(join(packageRoot, "dist/adapters/sqlite/sqlite-capsule-history.js")));
const { startStudio } = await import(pathToFileURL(join(packageRoot, "dist/adapters/studio/studio-server.js")));
const root = await realpath(await mkdtemp(join(tmpdir(), "contextforge-studio-browser-")));
let browser, studio, history;
try {
  await mkdir(join(root, "src"));
  for (let i = 0; i < 12; i++) await writeFile(join(root, "src", `ledger${i}.ts`), `export function ledger${i}() {\n${Array.from({ length: 24 }, (_, n) => `  const value${n} = 'source_value_${i}_${n}';`).join("\n")}\n  return 'ledger';\n}\n`);
  await writeFile(join(root, "AGENTS.md"), "# Rules\nVerify changed ledger behavior.\n");
  await writeFile(join(root, ".env"), "STUDIO_BROWSER_SECRET=never_read\n");
  const app = await createContextForgeLifecycle(root);
  history = new SqliteCapsuleHistory(join(root, ".contextforge/history"));
  studio = await startStudio(app, history);
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1512, height: 1080 } });
  const errors = []; page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(studio.url);
  await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  await page.getByText("Compile a coding task", { exact: true }).click();
  await page.getByRole("button", { name: "Compile & save", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Compiled and saved" }).waitFor();
  assert.ok(await page.locator("#candidates tr").count() > 1);
  await page.getByRole("button", { name: "Exact context", exact: true }).click();
  assert.ok((await page.locator("#payload").textContent()).includes("ContextForge Context Pack"));
  assert.ok(!(await page.locator("body").textContent()).includes("STUDIO_BROWSER_SECRET"));
  await page.getByRole("button", { name: "Context proposal", exact: true }).click();
  await page.locator("#candidates tr").filter({ has: page.locator(".tag.SELECTED") }).first().getByRole("button").click();
  await page.getByRole("status").filter({ hasText: "Explain: OK" }).waitFor();
  assert.ok((await page.locator("#explain").textContent()).includes("RECORDED DECISION"));
  await page.locator("#filter").selectOption("DROPPED");
  const droppedRow = page.locator("#candidates tr").first(); await droppedRow.getByRole("button").click();
  await page.getByRole("status").filter({ hasText: "Explain: OK" }).waitFor();
  await droppedRow.getByRole("combobox").selectOption("PIN");
  await page.getByRole("button", { name: "Coverage & lint", exact: true }).click();
  assert.ok((await page.locator("#coverage").textContent()).includes("BOUNDED CANDIDATES"));
  await page.getByRole("button", { name: "Recompile & compare", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "New Capsule saved" }).waitFor();
  assert.ok((await page.locator("#changes").textContent()).includes("DROPPED → SELECTED"));
  await page.getByRole("button", { name: "Replay", exact: true }).click();
  await page.getByRole("button", { name: "Verify replay", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Replay: EXACT_MATCH" }).waitFor();
  await page.reload(); await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  assert.equal(await page.locator(".history-entry").count(), 2);
  await page.locator(".history-entry").first().click();
  await page.getByRole("status").filter({ hasText: "Saved metadata opened" }).waitFor();
  await page.getByRole("button", { name: "Context proposal", exact: true }).click();
  await page.locator("#filter").selectOption("ALL");
  await page.locator("#candidates tr").first().getByRole("button").click();
  await page.getByRole("status").filter({ hasText: "Explain: OK" }).waitFor();
  const screenshots = resolve(".studio-output"); await mkdir(screenshots, { recursive: true });
  await page.screenshot({ path: join(screenshots, "studio-workflow.png"), fullPage: true });
  await page.locator("#task-composer").evaluate((e) => { e.open = true; });
  await page.locator("#task").fill("fix ledger <img src=x onerror=window.contextforgeInjected=true>");
  await page.locator("#refresh").uncheck();
  await page.getByRole("button", { name: "Compile & save", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "Compiled and saved" }).waitFor();
  assert.equal(await page.locator("img").count(), 0);
  assert.equal(await page.evaluate(() => globalThis.contextforgeInjected), undefined);
  await page.reload(); await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  assert.equal(await page.locator("img").count(), 0);
  assert.deepEqual(errors, []);
  // Restart proves durability and that historical source context is not persisted.
  await studio.close(); history.close(); history = new SqliteCapsuleHistory(join(root, ".contextforge/history"));
  studio = await startStudio(app, history); await page.goto(studio.url);
  await page.getByRole("status").filter({ hasText: "Ready." }).waitFor();
  await page.locator(".history-entry").first().click(); await page.getByRole("button", { name: "Exact context", exact: true }).click();
  assert.ok((await page.locator("#payload").textContent()).includes("Exact context is not stored"));
  console.log(JSON.stringify({ schemaVersion: "contextforge-studio-e2e-v1", passed: 1, failed: 0, skipped: 0, journey: ["compile", "context", "selected-explain", "dropped-explain", "coverage", "history", "pin", "recompile", "semantic-diff", "exact-replay", "reload", "stored-xss", "restart-source-light"], packageRoot: process.argv[2] ? "INSTALLED_PACKAGE" : "WORKTREE", browser: await browser.version() }));
} finally { await browser?.close(); await studio?.close(); history?.close(); await rm(root, { recursive: true, force: true }); }
